version: "3.9"
services:
  edge:
    image: nginx:alpine
    container_name: edge-proxy
    restart: unless-stopped
    ports:
      - "80:80"                      # add "443:443" after TLS is configured
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./html:/var/www/html
     # - ./logs:/var/log/nginx  # only if you really mount logs
    networks:
      - webapp_internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
networks:
  webapp_internal:
    external: true 
    name: webapp_internal

