version: "3.9"
services:
  wp-php:
    image: wordpress:php8.3-fpm-alpine
    container_name: wp-php
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./html:/var/www/html
      - ./ca-cert.pem:/var/www/html/ca-cert.pem:ro
      - ./ca-cert.pem:/etc/ssl/certs/db-ca.pem:ro
    networks:
      - internal  # Only internal - no external access
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3

  wp-mysql:
    image: mysql:8.0
    container_name: wp-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ca-cert.pem:/etc/ssl/certs/db-ca.pem:ro
    networks:
      - internal
    command: --default-authentication-plugin=mysql_native_password --ssl-ca=/etc/ssl/certs/db-ca.pem --ssl-mode=REQUIRED
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwordpress"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  wp-nginx:
    image: nginx:1.27-alpine
    container_name: wp-nginx
    restart: unless-stopped
    depends_on:
      - wp-php
    volumes:
      - ./html:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    networks:
      - internal      # Talk to PHP
      - webapp_internal  # Accept from edge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config/config.yml:ro
      - ./cloudflared/credentials.json:/etc/cloudflared/credentials.json:ro
    networks:
      - webapp_internal      # Connect to edge-nginx
      - webapp_webapp_internal  # Keep connection to wp-nginx
    ports:
      - "7844:7844/udp"  # QUIC port for tunnel
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
  webapp_internal:
    driver: bridge  # Create the shared network
  webapp_webapp_internal:
    driver: bridge  # Network for cloudflared to wp-nginx communication