version: "3.9"
services:
  wp-php:
    image: wordpress:php8.3-fpm-alpine
    container_name: wp-php
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./html:/var/www/html
      - ./ca-cert.pem:/etc/ssl/certs/db-ca.pem:ro
    networks:
      - internal  # Only internal - no external access
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3

  wp-nginx:
    image: nginx:1.27-alpine
    container_name: wp-nginx
    restart: unless-stopped
    depends_on:
      - wp-php
    volumes:
      - ./html:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    networks:
      - internal      # Talk to PHP
      - webapp_internal  # Accept from edge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  internal:
    driver: bridge
  webapp_internal:
    driver: bridge  # Create the shared network