services:
  wp-php:
    image: wordpress:php8.3-fpm-alpine
    container_name: wp-php
    restart: unless-stopped
    env_file: .env              # ← loads DB vars from /opt/webapp/.env
    volumes:
      - ./html:/var/www/html
      - ./ca-cert.pem:/etc/ssl/certs/db-ca.pem:ro
    networks: [internal]

  wp-nginx:
    image: nginx:1.27-alpine
    container_name: wp-nginx
    restart: unless-stopped
    depends_on:
      - wp-php
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"                   # ← internal-only; no host port
    networks:
      - internal
      - webapp_internal

networks:
  internal:
    driver: bridge
    webapp_internal:
      external: true
      name: webapp_internal
